<?php

namespace ForumBundle\Repository;

/**
 * AimeFRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AimeFRepository extends \Doctrine\ORM\EntityRepository
{
    public function aimeByQuestion($id)
    {
        $qb = $this->createQueryBuilder('c')
            ->select('COUNT(c)')
            ->where('c.id_question= :idQ')
            ->setParameter('idQ', $id);
        return $qb->getQuery()->getSingleScalarResult();
    }

    public function findaimes($id)
    {
        $q=$this->getEntityManager()
            ->createQuery("SELECT m FROM ForumBundle:AimeF m WHERE m.id_question=:id ")
            ->setParameter(":id",$id);
        return $q->getResult();
    }

    public function findeverything($id)
    {
        $q=$this->getEntityManager()
            ->createQuery("select v from ForumBundle:AimeF v  where v.id_user=:iduser ")
            ->setParameter(":iduser",$id)
            ->setMaxResults(1)
        ;
        return $q->getOneOrNullResult();
    }

    public function findeverythingQ($id)
    {
        $q=$this->getEntityManager()
            ->createQuery("select v from ForumBundle:AimeF v  where v.id_question=:id ")
            ->setParameter(":id",$id)
            ->setMaxResults(1)
        ;
        return $q->getOneOrNullResult();

    }

}
