<?php

namespace ForumBundle\Repository;

/**
 * CommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireRepository extends \Doctrine\ORM\EntityRepository
{
    public function findC($id)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('u')
            ->from($this->_entityName, 'u')
            ->where('u.id_question = :idQ')
            ->setParameter('idQ', $id);
        return $qb->getQuery()->getResult();
    }



    public function commentaireByQuestion($id)
    {
        $qb = $this->createQueryBuilder('c')
            ->select('COUNT(c)')
            ->where('c.id_question= :idQ')
            ->setParameter('idQ', $id);
        return $qb->getQuery()->getSingleScalarResult();
    }
}
