<?php

namespace ForumBundle\Repository;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends \Doctrine\ORM\EntityRepository
{
    public function findquest($id)
    {
        $q=$this->getEntityManager()
            ->createQuery("SELECT m FROM ForumBundle:Question m WHERE m.categorie=:id")
            ->setParameter(":id",$id);
        return $q->getResult();
    }

    public function questionBycategorie($id)
    {
        $qb = $this->createQueryBuilder('c')
            ->select('COUNT(c)')
            ->where('c.categorie= :id')
            ->setParameter('id', $id);
        return $qb->getQuery()->getSingleScalarResult();
    }
    public function findquestplusaime()
    {
        $q=$this->getEntityManager()
            ->createQuery("SELECT m FROM ForumBundle:Question m ORDER BY m.nbrjaimes DESC ");
        return $q->getResult();
    }
    public function findquestpluscommente()
    {
        $q=$this->getEntityManager()
            ->createQuery("SELECT m FROM ForumBundle:Question m ORDER BY m.nbrcommentaire DESC ");
        return $q->getResult();
    }


}
